apiVersion: v1
kind: PersistentVolume
metadata:
  name: black-pv-cka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/black-pv-cka"